services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  archive:
    image: registry.impending.org:5050/archive:latest
    command: courtyard:12345
    environment:
      - DB_CONNECT=${DB_ARCHIVE}
    depends_on:
      db:
        condition: service_healthy
      courtyard:
        condition: service_started
  bazaar:
    image: registry.impending.org:5050/bazaar:latest
    command: courtyard:12345
    environment:
      - DB_CONNECT=${DB_BAZAAR}
    depends_on:
      db:
        condition: service_healthy
      courtyard:
        condition: service_started
  courtyard:
    image: registry.impending.org:5050/courtyard:latest
    ports:
      - "12345:12345"
  drawbridge:
    image: registry.impending.org:5050/drawbridge:latest
    command: courtyard:12345
    ports:
      - "23450:23450"
    depends_on:
      courtyard:
        condition: service_started
  forum:
    image: registry.impending.org:5050/forum:latest
    command: courtyard:12345
    depends_on:
      courtyard:
        condition: service_started
  gate:
    image: registry.impending.org:5050/gate:latest
    command: courtyard:12345
    ports:
      - "23451:23451"
    depends_on:
      courtyard:
        condition: service_started
  hall:
    image: registry.impending.org:5050/hall:latest
    command: courtyard:12345
    depends_on:
      courtyard:
        condition: service_started
  jail:
    image: registry.impending.org:5050/jail:latest
    command: courtyard:12345
    depends_on:
      courtyard:
        condition: service_started
  lookout:
    image: registry.impending.org:5050/lookout:latest
    command: courtyard:12345
    environment:
      - DB_CONNECT=${DB_LOOKOUT}
    depends_on:
      db:
        condition: service_healthy
      courtyard:
        condition: service_started
  warehouse:
    image: registry.impending.org:5050/warehouse:latest
    ports:
      - "23235:23235"
volumes:
  pgdata:
