services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  archive:
    build:
      context: ./crates
      dockerfile: archive/Dockerfile
    image: ${REGISTRY}/archive:latest
    command: courtyard:12345
    environment:
      - DB_CONNECT=${DB_ARCHIVE}
    depends_on:
      db:
        condition: service_healthy
      courtyard:
        condition: service_started
  bazaar:
    build:
      context: ./crates
      dockerfile: bazaar/Dockerfile
    image: ${REGISTRY}/bazaar:latest
    command: courtyard:12345
    environment:
      - DB_CONNECT=${DB_BAZAAR}
    depends_on:
      db:
        condition: service_healthy
      courtyard:
        condition: service_started
  courtyard:
    build:
      context: ./crates
      dockerfile: courtyard/Dockerfile
    image: ${REGISTRY}/courtyard:latest
    ports:
      - "12345:12345"
  drawbridge:
    build:
      context: ./crates
      dockerfile: drawbridge/Dockerfile
    image: ${REGISTRY}/drawbridge:latest
    command: courtyard:12345
    ports:
      - "23450:23450"
    depends_on:
      courtyard:
        condition: service_started
  forum:
    build:
      context: ./crates
      dockerfile: forum/Dockerfile
    image: ${REGISTRY}/forum:latest
    command: courtyard:12345
    depends_on:
      courtyard:
        condition: service_started
  gate:
    build:
      context: ./crates
      dockerfile: gate/Dockerfile
    image: ${REGISTRY}/gate:latest
    command: courtyard:12345
    ports:
      - "23451:23451"
    depends_on:
      courtyard:
        condition: service_started
  hall:
    build:
      context: ./crates
      dockerfile: hall/Dockerfile
    image: ${REGISTRY}/hall:latest
    command: courtyard:12345
    depends_on:
      courtyard:
        condition: service_started
  jail:
    build:
      context: ./crates
      dockerfile: jail/Dockerfile
    image: ${REGISTRY}/jail:latest
    command: courtyard:12345
    depends_on:
      courtyard:
        condition: service_started
  lookout:
    build:
      context: ./crates
      dockerfile: lookout/Dockerfile
    image: ${REGISTRY}/lookout:latest
    command: courtyard:12345
    environment:
      - DB_CONNECT=${DB_LOOKOUT}
    depends_on:
      db:
        condition: service_healthy
      courtyard:
        condition: service_started
  warehouse:
    build:
      context: ./crates
      dockerfile: warehouse/Dockerfile
    image: ${REGISTRY}/warehouse:latest
    ports:
      - "23235:23235"
volumes:
  pgdata:
