[package]
name = "lookout"
description = "Lookout is the user authentication service."
version = "0.1.0"
edition = "2021"
authors = ["Scott Barcik <oxooo5co77@impending.org>"]

[dependencies]
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.8.2", features = ["postgres", "macros", "uuid", "runtime-tokio-rustls"] }
uuid = { version = "1.11.0", features = ["v4"] }
shared-data = { path = "../shared-data" }
shared-net = { path = "../shared-net" }

[dev-dependencies]
fasthash = { version = "0.4.0" }
