[package]
name = "vagabond"
description = "Vagabond is the Bevy-based game client."
version = "0.1.0"
edition = "2021"
authors = ["Scott Barcik <oxooo5co77@impending.org>"]
default-run = "vagabond"

[dependencies]
anyhow = { version = "1.0.89" }
bevy = { version = "0.14.2" }
bevy_egui = { version = "0.30.0", features = ["immutable_ctx"] }
chrono = { version = "0.4.38", default-features = false, features = ["std", "serde"] }
fasthash = { version = "0.4.0" }
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
rand = { version = "0.8.5" }
ron = { version = "0.8.1" }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128" }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
shared-data = { path = "../shared-data" }
shared-net = { path = "../shared-net" }
hall = { path = "../hall" }
warehouse = { path = "../warehouse" }
