[package]
name = "vagabond"
description = "Vagabond is the Bevy-based game client."
version = "0.1.0"
edition = "2021"
authors = ["Scott Barcik <oxooo5co77@impending.org>"]
default-run = "vagabond"

[dependencies]
anyhow = { version = "1.0.92" }
bevy = { version = "0.14.2" }
bevy_egui = { version = "0.30.0", features = ["immutable_ctx"] }
chrono = { version = "0.4.38", default-features = false, features = ["std", "serde"] }
fasthash = { version = "0.4.0" }
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
rand = { version = "0.9.0-alpha.2" }
ron = { version = "0.9.0-alpha.0" }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = { version = "1.0.132" }
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
shared-data = { path = "../shared-data" }
shared-net = { path = "../shared-net" }
hall = { path = "../hall" }
warehouse = { path = "../warehouse" }
pyri_tooltip = "0.1.1"
