[package]
name = "archive-lib"
description = "Archive is the game object inventory service."
version = "0.1.0"
edition = "2021"
authors = ["Scott Barcik <oxooo5co77@impending.org>"]

[dependencies]
num_enum = "0.7.3"
