#!/bin/bash
podman build -f archive/Dockerfile . -t "$(REGISTRY)/archive:latest"
podman build -f bazaar/Dockerfile . -t "$(REGISTRY)/bazaar:latest"
podman build -f courtyard/Dockerfile . -t "$(REGISTRY)/courtyard:latest"
podman build -f drawbridge/Dockerfile . -t "$(REGISTRY)/drawbridge:latest"
podman build -f forum/Dockerfile . -t "$(REGISTRY)/forum:latest"
podman build -f gate/Dockerfile . -t "$(REGISTRY)/gate:latest"
podman build -f hall/Dockerfile . -t "$(REGISTRY)/hall:latest"
podman build -f jail/Dockerfile . -t "$(REGISTRY)/jail:latest"
podman build -f lookout/Dockerfile . -t "$(REGISTRY)/lookout:latest"
podman build -f watchtower/Dockerfile . -t "$(REGISTRY)/watchtower:latest"

podman push "$(REGISTRY)/archive:latest"
podman push "$(REGISTRY)/bazaar:latest"
podman push "$(REGISTRY)/courtyard:latest"
podman push "$(REGISTRY)/drawbridge:latest"
podman push "$(REGISTRY)/forum:latest"
podman push "$(REGISTRY)/gate:latest"
podman push "$(REGISTRY)/hall:latest"
podman push "$(REGISTRY)/jail:latest"
podman push "$(REGISTRY)/lookout:latest"
podman push "$(REGISTRY)/watchtower:latest"
