[package]
name = "bufferable-derive"
description = "#[derive(Bufferable)]"
version = "0.1.0"
edition = "2024"
authors = ["Scott Barcik <oxooo5co77@impending.org>"]

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0.41" }
syn = { version = "2.0.106", features = ["full"] }
